apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd-prod
resources:
  - ../../base
  - ingress.yaml
  - web-pdb.yaml
images:
  - name: demo
    newName: ghcr.io/rafilo/cicd-playground
    digest: sha256:8d19c52594e223120504ac21557e965143bf114d26ef3fd279f810c09687854f
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/minReadySeconds
        value: 5
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            matchLabelKeys: [app]
            labelSelector:
              matchLabels:
                app.kubernetes.io/part-of: cicd-production
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
        value: cicd-production
  - target:
      kind: Deployment
      name: demo-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
