deployment:
  replicas: 2
providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: true
    namespaces:
      - cicd-prod
  kubernetesGateway:
    enabled: false
gateway:
  enabled: false
ingressRoute:
  dashboard:
    enabled: false
service:
  type: NodePort
ports:
  web:
    nodePort: 30080
  websecure:
    expose:
      default: false
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
        topologyKey: kubernetes.io/hostname
