apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd-demo
resources: [../../base]
images:
  - name: demo
    newName: ghcr.io/rafilo/cicd-playground
    digest: sha256:08c9288f9c847d25109ea943ab9401ef3c382cf18eee6f4ba7b04e9669390f42
